name: Continuous Integration
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: reg-viz/reg-actions@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          image-directory-path: "__screenshots__"
          artifact-name: "test"
